# Permalinks
permalink:           pretty

# Setup
title:            Nicolas Massé
tagline:          Informatique et BTP
url:              http://www.itix.fr
paginate:         1
baseurl:          /
author:
  name:           Nicolas Massé
  url:            https://fr.linkedin.com/in/nicolasmasse
  email:          nicolas.masse@itix.fr

# Custom vars
version:             2.0.0
github:
  repo:           https://github.com/nmasse-itix/nmasse-itix.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
